Feature: Criando service de products que faz validação
GabrielEssenio/Mercado-Livre-Frescos pull request #9
Opened 2022-04-25 21:32 UTC by GabrielEssenio

2022-04-26 17:56 UTC, GabrielEssenio commented
Service de products finalizado, se puderem fazer o review.
por favor

2022-04-27 11:52 UTC, wevertonbruno requested changes

2022-04-27 11:52 UTC, wevertonbruno commented on src/main/java/com/mercadolibre/grupo1/projetointegrador/dtos/ExceptionNotFound.java
> +public class ExceptionNotFound {
Essa classe nao precisa existir. ELa faz a mesma coisa do ExceptionDTO. Se quiser retornar um notFound, cria no ExceptionDTO um metodo construtor notFound:
`public static ExceptionDTO notFound()...`

2022-04-27 11:52 UTC, wevertonbruno commented on src/main/java/com/mercadolibre/grupo1/projetointegrador/exceptions/ExceptionCatchIsEmpty.java
> +public class ExceptionCatchIsEmpty extends RuntimeException {
Vamo padronizar as exceptions para DESCRICAO + Exception
```suggestion
public class ListIsEmptyException extends RuntimeException {
```

2022-04-27 11:52 UTC, wevertonbruno commented on src/main/java/com/mercadolibre/grupo1/projetointegrador/exceptions/ExceptionCatchStatusCategory.java
> +public class ExceptionCatchStatusCategory extends RuntimeException{
Vamo padronizar as exceptions para DESCRICAO + Exception
```suggestion
public class InvalidCategoryException extends RuntimeException{
```

2022-04-27 11:52 UTC, wevertonbruno commented on src/main/java/com/mercadolibre/grupo1/projetointegrador/services/ProductService.java
> +    public List<ProductDTO> listAllProducts() throws ExceptionCatchIsEmpty {
tira esse throws como é uma RuntimeException ela vai ser capturada no Advice.
```suggestion
    public List<ProductDTO> listAllProducts(){
```

2022-04-27 11:52 UTC, wevertonbruno commented on src/main/java/com/mercadolibre/grupo1/projetointegrador/services/ProductService.java
> +    public List<ProductDTO> listProductByCategory(String productCategory) throws ExceptionCatchIsEmpty {
Mesma ideia aqui, nn precisa do throws
```suggestion
    public List<ProductDTO> listProductByCategory(String productCategory){
```

2022-04-27 12:02 UTC, wevertonbruno requested changes

2022-04-27 12:02 UTC, wevertonbruno commented on src/main/java/com/mercadolibre/grupo1/projetointegrador/services/ProductService.java
> +    public List<ProductDTO> listProductByCategory(ProductCategory productCategory) throws ExceptionCatchIsEmpty {
```suggestion
    public List<ProductDTO> listProductByCategory(ProductCategory productCategory){
```

2022-04-27 12:02 UTC, wevertonbruno commented
Botei uma classe de config na sua branch pra tratar a conversao de ProductCategory. Achei essa solucao mais bonita :D

2022-04-27 12:53 UTC, GabrielEssenio commented on src/main/java/com/mercadolibre/grupo1/projetointegrador/exceptions/ExceptionCatchIsEmpty.java
> +public class ExceptionCatchIsEmpty extends RuntimeException {
Beleza!
Vou mudar a descrição para a padronização

2022-04-27 12:54 UTC, GabrielEssenio commented on src/main/java/com/mercadolibre/grupo1/projetointegrador/dtos/ExceptionNotFound.java
> +public class ExceptionNotFound {
Tranquilo!
Vou passar essa classe pra dentro de ExceptionDTO

2022-04-27 12:55 UTC, GabrielEssenio commented on src/main/java/com/mercadolibre/grupo1/projetointegrador/exceptions/ExceptionCatchStatusCategory.java
> +public class ExceptionCatchStatusCategory extends RuntimeException{
Beleza!
Vou mudar a descrição para a padronização

2022-04-27 12:55 UTC, GabrielEssenio commented on src/main/java/com/mercadolibre/grupo1/projetointegrador/services/ProductService.java
> +    public List<ProductDTO> listAllProducts() throws ExceptionCatchIsEmpty {
👍

2022-04-27 12:55 UTC, GabrielEssenio commented on src/main/java/com/mercadolibre/grupo1/projetointegrador/services/ProductService.java
> +    public List<ProductDTO> listProductByCategory(String productCategory) throws ExceptionCatchIsEmpty {
👍

2022-04-28 13:30 UTC, GabrielEssenio commented
Testes unitarios concluidos!

2022-04-29 12:43 UTC, wevertonbruno approved these changes

2022-04-29 12:46 UTC, wevertonbruno commented
Show demais!

2022-04-29 17:08 UTC, wevertonbruno requested changes

2022-04-29 17:08 UTC, wevertonbruno commented on src/main/java/com/mercadolibre/grupo1/projetointegrador/controller/PurchaseOrderController.java
> +    public ResponseEntity<List<ProductDTO>> listAllProduct(){
Acho que seria mais interessante passar esses endpoints para um ProductController, nn ta fazendo muito sentido ele ta em purchaseOrder. Que ce acha?

2022-04-29 20:46 UTC, GabrielEssenio commented on src/main/java/com/mercadolibre/grupo1/projetointegrador/controller/PurchaseOrderController.java
> +    public ResponseEntity<List<ProductDTO>> listAllProduct(){
Faz mais sentido sim @wevertonbruno 
Vou separar os Controller que são de Product

2022-04-29 21:53 UTC, merged